/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/assets/avatar.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="real_armature" position={[0.54, 0, 0]}>
          <primitive object={nodes.Bone02R} />
          <primitive object={nodes.Bone09L} />
          <group name="Plane006">
            <skinnedMesh
              name="Plane007"
              geometry={nodes.Plane007.geometry}
              material={materials.Material}
              skeleton={nodes.Plane007.skeleton}
            />
            <skinnedMesh
              name="Plane007_1"
              geometry={nodes.Plane007_1.geometry}
              material={materials["Material.003"]}
              skeleton={nodes.Plane007_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/avatar.glb");